<?php

return [
    [
        "title"            => "Spotify Web",
        "author"           => "Pierluca Strianese",
        "creation_date"    => "2023-03-23",
        "last_update"      => "2023-03-24",
        "collaborators"    => "",
        "description"      => "A clone of Spotify Web",
        "languages"        => "HTML, CSS",
        "link_github"      => "https://github.com/Pierluca-Strianese/html-css-spotifyweb",
    ],
    [
        "title"            => "Campominato",
        "author"           => "Pierluca Strianese",
        "creation_date"    => "2023-04-26",
        "last_update"      => "2023-04-28",
        "collaborators"    => "",
        "description"      => "A clone of Minefield ",
        "languages"        => "HTML, CSS, JS ",
        "link_github"      => "https://github.com/Pierluca-Strianese/js-campominato-dom",
    ],
    [
        "title"            => "Social Post",
        "author"           => "Pierluca Strianese",
        "creation_date"    => "2023-05-10",
        "last_update"      => "2023-05-10",
        "collaborators"    => "",
        "description"      => "A clone of Facebook",
        "languages"        => "HTML, CSS, JS",
        "link_github"      => "https://github.com/Pierluca-Strianese/js-social-posts",
    ],
    [
        "title"            => "BoolzApp",
        "author"           => "Pierluca Strianese",
        "creation_date"    => "2023-05-10",
        "last_update"      => "2023-05-15",
        "collaborators"    => "",
        "description"      => "A clone of WhatsApp",
        "languages"        => "HTML, CSS, JS",
        "link_github"      => "https://github.com/Pierluca-Strianese/vue-boolzapp",
    ],
    [
        "title"            => "BoolFlix",
        "author"           => "Pierluca Strianese",
        "creation_date"    => "2023-05-25",
        "last_update"      => "2023-06-1",
        "collaborators"    => "",
        "description"      => "A clone of Nelflix",
        "languages"        => "HTML, JS, VUE",
        "link_github"      => "https://github.com/Pierluca-Strianese/vite-boolflix",
    ],
    [
        "title"            => "DC Comics",
        "author"           => "Pierluca Strianese",
        "creation_date"    => "2023-06-29",
        "last_update"      => "2023-07-03",
        "collaborators"    => "",
        "description"      => "A clone of a Website of DC Comics",
        "languages"        => "PHP, BLADE",
        "link_github"      => "https://github.com/Pierluca-Strianese/laravel-dc-comics",
    ],
];
